### ISSUE TITLE
Copy/paste functionality

### ISSUE THREAD

**Issue by ktb92677** [vurtun/gui#4]
Hey! So do you think you'll have copy and paste functionality built into this soon?

Thank you so much for all the time you are putting into this by the way!

**Comment by vurtun** [comment]
Actual system coping from/to clipboard is not planned, since it would require a lot of quite ugly platform dependent code that only a selected group would benefit from. Instead what I could do is provide a callback for coping out of a editbox and the user would then have to copy it to the clipboard. 
As for pasting, that is even more difficult but could maybe be implemented with a callback as well.
So if you would be fine with just having callbacks than I could implement it in the near future.

**Comment by ktb92677** [comment]
No no, I'm not by any means suggesting you implement any platform dependent code. (this and the simplicity of your library are the reasons why I've decided to use your GUI system over others) But what would be nice is like I want to be able to highlight text and right click and copy and right click to paste and such. Let the programmers fill in the platform related stuff as you have done with most everything else

**Comment by vurtun** [comment]
This could get a little bit more complicated so I cannot make any promises that I can finish it this week since I have to take a break for a few weeks to learn for my final exams.

**Comment by ktb92677** [comment]
Great! Thanks, I look forward to the update

**Comment by vurtun** [comment]
I added basic copy & paste of a user specified string for input boxes over callback. But for it to work you have to use the newly created `struct editbox` and the `gui_panel_editbox` API call and provided a copy & paste key input in `struct gui_input`. The actual key in this case does not matter so you could even use key combinations. The old versions with `gui_panel_edit` and `gui_panel_edit_filterered` are not affected and still do not have copy & paste but are still working. In addition the `struct editbox` does not have a freely movable cursor or text selection as for now, but maybe with a little bit of luck I can create a version with it tomorrow.

**Comment by ktb92677** [comment]
Just a quick note here! Looks like the cursor doesn't adjust properly when you click backspace! Still testing your copy paste stuff. I'll give you an update soon.

As always thanks for all of your development time here!

**Comment by vurtun** [comment]
Hey,
the backspace behavior at least with ASCII seems to work fine for me, at least in the demos with absolutely correct font handling (nanovg, xlib). But I found a different bug for UTF-8. I decrement and therefore remove one character from the back of the editbox buffer. But actually I need to remove the last glyph, so it could very well be that your problem stems from that bug.

**Comment by ktb92677** [comment]
Okay, so is this something I can implement or does it have to be modified on your end?

**Comment by vurtun** [comment]
I removed the bug so if it does not work now than I it looks like it is on your end.

**Comment by ktb92677** [comment]
Thanks a bunch!

**Comment by ktb92677** [comment]
Kind of more of a interpretive question, but are you planning on continuing to add more kinds of widgets and expand the features of this toolkit? I'm implementing this toolkit on a relatively large platform and continued development would put my heart to ease. No pressure obviously but I'm just curious what phase this project is in for you.

**Comment by vurtun** [comment]
OK this will be a little bit more personal. Like I already said I am currently in my last semester in university and I am currently studying for my last finals. Which means that the next few month are unpredictable and will probably contain a lot of change for me. So I cannot 100% guarantee that I will have as much time as I had while writing this library.
That being said I am personally committed to this library and use it myself to write an GDB debugger frontend (the file explorer screenshot in the gallery is from that project) to finally have a good linux debugger and learn more about this library in practice and find and extend it's boundaries and fix or add things that I personally need.
As for adding new widgets this is a complicated issue. First of if you need something just create a new issue and I will think about it and if possible create it. But to make things clear there are classic widget types in retain mode GUI's like combo boxes, trees and menus that I do not want to create since they can be replaced or simulated by using the already existing functionality and adding them would cause  headache, consume a lot of time/energy and would complicate the library extremely. So if you have a certain widget that you would like to have create an issue and I will either create it, show a different way to achieve the same goal or deny it (example.: combo boxes) since it would be to complicated to create.
