### ISSUE TITLE
Layout (x,y placement)

### ISSUE THREAD

**Issue by ktb92677** [vurtun/gui#5]
I noticed that widgets can be placed in a layout in the panel, but is there an option to add widgets at an x, y location? (and to specify width and height) Like sort of a null layout.

Can this feature be added? (or does it already exist?)

Thanks!

**Comment by vurtun** [comment]
The panel is implemented around the concept of a row that is being filled with a number of widgets. The reason for this is that panels are completely height independent (since tabs have no concept of panel height). Therefore having completely dynamic Y-Position for widgets in panels is not really an option since I would have to rethink and reimplement a big chunk of the library. As for the X-Position they as well cannot be set to an arbitrary position. But a different approach can be taken by using the three different layout control functions.

I.) Table layout
A table row created with `gui_panel_row` sets the row with a height and a number of widgets. The widgets bounds and x-position for every widget is then used. In addition if a roughly fixed pixel width is needed you can calculate the number of widgets that fit into that row with the helper function `gui_panel_row_columns`. This is not pixel perfect but the closest you can get with a table layout.

II.) User controlled layout
To support widgets with different width I added the `gui_panel_row_templated` function. With it you can describe the height, number of widgets inside the row as well as an array with ratios for the width of every widget in relation to the panel width. So if you have an non-scaleable panel you can set the the pixel width of every widget (`widget_pixels_size/layout.width`). The slider + label in the demo was implemented that way you if you need an example have a look.

III.) Seperators
While the user controlled layout can specify the widget width, the x-position of an widgets is still static (the y-position is controlled over the row functionality). For that to change I have a additional utility function `gui_panel_spacing`. It can be used to overstep single or multiple widget slots or even rows. 

IV) Combining
So if you combine the user controlled layout and the seperator you get on rows limited arbitrary widget placement and size. Example:
- panel with size (w: 200 px. h: 400 px)
- button to add at local position and size of (x: 100 px, y: 100 px, w: 50 px, h: 50 px)
```c
struct gui_panel_layout layout
gui_panel_begin(...); // to lazy to fill out
gui_panel_row(100, 0); // skipping row to get to y-position
/* To note is that you can only go downwards while filling the panel therefore you cannot add widgets into y positions 0 - 100 px from this point onwards */
gui_float ratios[] = {100.0f/layout.width, 50.0f/layout.width, GUI_UNDEFINED};
gui_panel_row_templated(50, 3, ratios);
gui_panel_spacing(&layout, 1);
if (gui_panel_button_text(&layout, "Button", GUI_BUTTON_DEFAULT))
    /* event handling */
gui_panel_end(...) // to lazy to fill out
```

**Comment by ktb92677** [comment]
Hey, a question on this right here, however I was looking through gui,h and I found the following: "gui_button_text" which is a function which seemingly lets me place widgets at x, y locations. Are these functions depreciated?

**Comment by vurtun** [comment]
Hey,
almost every widget in the panel API has a widget API version, which are more complicated but provide complete free positional placing and style. They need more arguments and are the base of every widget inside the panel API (have a look at the panel API you can see that almost all of them just call the widget API functions). The biggest problem with them is that they do not work within a dynamic panels (mimizing, scaling, moving) directly. But if you do not need a panel and are willing to do the extra work then they provide a lot more freedom.

**Comment by vurtun** [comment]
Ok I thought about it. There is a way to create widgets inside a panel at a definite position and size.
But it is complex and should only be used if all what I previously wrote about (table layout, User controlled layout, Seperator, and widget grouping) is not enough or failed. The reason I was hesitant to describe it, was to spare you from doing the most complicated way to achieve a layout, since the methods I previously described are way easier and provide good results in probably 99% of the time.

So this is a little bit more complicated. First of it is important to now that the basic idea behind my gui implementation is a canvas in form of a panel that can be filled with whatever is needed inside a frame and that is based on dynamic changes. The panel is hereby divided by either using the table layout or user controlled layout. This works fine for the panel API widgets and should bring reasonable result in most cases. The space inside the panel is hereby `allocated` from the panel and by that I mean the panel grows with each widget internally.

So what you could do is use one of the two layouts and just allocated space from the panel that you use for your purpose and fill up with widgets from the widget API (notice not the panel API) by directly placing the widgets inside the space. This is by the way almost the same procedure if you want to create a new widget type. The question is of course how to allocated space. This is done by a public helper function that every widget inside the panel API uses, `gui_panel_widget`. It takes the panel layout and a `gui_rect` struct and fills the `gui_rect` with the position and size of the allocated space inside the panel. In addition it returns `gui_true` if the space is valid or `gui_false` if not. Valid in this particular case means if the space is visible and therefore should be drawn. This happens for example if the panel is hidden or minimized. So the best way to describe it is by code:

```c
/* these two describe the style and color of the widgets */
const struct gui_slider slider = {...};
const struct gui_progress progress = {...};

gui_float value = 5.0f
gui_size prog = 20;

struct gui_panel_layout layout
gui_panel_begin(...); // to lazy to fill out

/* set the size of the to allocate space and allocate it */
struct gui_rect bounds;
gui_panel_row(200, 1); 
if (gui_widget(&bounds, &layout)) {
    // use the widget API to draw two widgets inside the allocated space it is important to know at which position inside the panel you are
    value = gui_slider(&layout.buffer, 50, 50, 100, 30, 0, value, 10, 1, &slider, &layout.buffer.input);
    prog = gui_progress(&layout.buffer, 50, 100, 100, 30, prog, 100, gui_false, &progress, &layout.buffer.input);
}
gui_panel_end(...) // to lazy to fill out
```

**Comment by ktb92677** [comment]
Thank you for the indepth description here. Just thought I'd let you know I have had no problems thus far using the methods you have described
