### ISSUE TITLE
Compilation fails under VS2013.

### ISSUE THREAD

**Issue by ongamex** [vurtun/gui#6]
Compilation fails under VS2013, there are a lot of errors, primarily typecasts.

**Comment by vurtun** [comment]
Thank for your feedback!.
Which demo did you try to compile the opengl, nanovg or win32 version or was the problem in the library itself? At the moment I do not have a windows system. So it will take till monday or tuesday to check and create project versions for visual studio.

**Comment by ongamex** [comment]
Excuse me for my previous comment, It really doesn't help at all

All I did is basically drag'n'drop "gui.c" into my project file and then hit Ctr+F7. The output log probably won't help you but here it is http://pastebin.com/CW4wnF7L .

**Comment by vurtun** [comment]
Ah ok a lot of the typecast problems have it source in the difference between C and C++. This is a problem on my side since I use ANSI C and only compiled in Visual Studio with the C compiler which allows for casting from void pointer to any type without typecast. I will fix it as soon as possible and try to get everything running under C++.

**Comment by vurtun** [comment]
OK I uploaded a new version that should be compileable under C++ at least it is for clang and gcc. If it still gives errors than I need to look at it again under windows.

**Comment by ongamex** [comment]
It compiles now! Thanks for the fast fix!

**Comment by vurtun** [comment]
OK great success. If you encounter any problems or if something is unclear feel free to just open another issue.
